
####
GET http://localhost:8080/curso-soflex/index.php/cliente
####
GET http://localhost:8080/curso-soflex/index.php/pais

####
GET http://localhost:8080/curso-soflex/index.php/cliente




###


POST http://localhost:8080/denuncias-api/index.php/denuncia HTTP/1.1
content-type: application/json; charset=UTF-8

{
    "deweCodigo": "ABC1234",
    "deweJSON": "{ZARAZA}"
}



###

POST https://sisep.soflex.com.ar/api/geocode/buscar HTTP/1.1
content-type: application/json; charset=UTF-8

{
    "direccion": "avenida corrientes 1234",
    "localidad": "COMUNA 1",
    "partido": "CABA"
}


